version: '3'

services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - netwp
     volumes:
       # managed volume (but could be a maped volume)
       - db_data:/var/lib/mysql
     # restart the container if docker stopped
     restart: always

   wordpress:
     depends_on:
       - db
     image: wordpress:5.3.2
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
       - netwp
     ports:
       - "8000:80"
     restart: always

volumes:
  db_data: {}

# a default network bridge is created but it is better to be explicit
networks:
  netwp: {}
